using System.Text;
using Microsoft.EntityFrameworkCore.Update;

namespace Couchbase.EntityFrameworkCore.Update.Internal;

/// <summary>
/// Generates SQL++ DML statements (INSERT, UPDATE, DELETE) for Couchbase Server.
/// </summary>
/// <remarks>
/// Couchbase SQL++ supports a native RETURNING clause, so this class extends
/// <see cref="UpdateSqlGenerator"/> directly (the RETURNING-based strategy) rather
/// than <c>UpdateAndSelectSqlGenerator</c> (the INSERT+SELECT strategy used by
/// SQL Server and SQLite).
///
/// The base class already produces correct SQL++ DML for INSERT, UPDATE, and DELETE
/// with RETURNING. This class adds Couchbase-specific behaviour on top:
/// <list type="bullet">
///   <item>No batch-level preamble (no equivalent of <c>SET NOCOUNT ON</c>).</item>
///   <item>No autocommit guard (no equivalent of <c>SET IMPLICIT_TRANSACTIONS OFF</c>).</item>
///   <item>No stored procedures — <see cref="AppendStoredProcedureCall"/> throws.</item>
///   <item>Sequence values use SQL++'s <c>SELECT NEXT VALUE FOR</c> syntax.</item>
/// </list>
///
/// SQL++ DML examples generated by the base class:
/// <code>
///   -- INSERT with generated-value read-back
///   INSERT INTO `airline` (`id`, `name`, `country`) VALUES ($p1, $p2, $p3)
///   RETURNING `id`, `name`, `country`;
///
///   -- UPDATE
///   UPDATE `airline` SET `name` = $p1, `country` = $p2
///   WHERE `id` = $p3
///   RETURNING `id`, `name`, `country`;
///
///   -- DELETE
///   DELETE FROM `airline`
///   WHERE `id` = $p1
///   RETURNING 1;
/// </code>
/// </remarks>
public class CouchbaseUpdateSqlGenerator : UpdateSqlGenerator
{
    public CouchbaseUpdateSqlGenerator(UpdateSqlGeneratorDependencies dependencies)
        : base(dependencies)
    {
    }

    // AppendBatchHeader: base default is a no-op, which is correct for Couchbase SQL++.
    // AppendInsertOperation: base emits INSERT … RETURNING when there are read columns.
    // AppendUpdateOperation: base emits UPDATE … SET … WHERE … RETURNING.
    // AppendDeleteOperation: base emits DELETE FROM … WHERE … RETURNING 1.
    // All of the above produce valid Couchbase SQL++.

    /// <summary>
    /// No-op: Couchbase SQL++ does not require an autocommit guard statement.
    /// </summary>
    public override void PrependEnsureAutocommit(StringBuilder commandStringBuilder)
    {
    }

    /// <summary>
    /// Couchbase does not expose stored procedures as DML targets.
    /// </summary>
    public override ResultSetMapping AppendStoredProcedureCall(
        StringBuilder commandStringBuilder,
        IReadOnlyModificationCommand command,
        int commandPosition,
        out bool requiresTransaction)
        => throw new NotSupportedException(
            "Couchbase SQL++ does not support stored procedure calls for entity DML operations.");

    /// <summary>
    /// Returns a SQL++ statement that reads the next value from a named sequence.
    /// </summary>
    /// <remarks>
    /// Couchbase SQL++ syntax: <c>SELECT NEXT VALUE FOR `scope`.`name`;</c>
    /// </remarks>
    public override string GenerateNextSequenceValueOperation(string name, string? schema)
    {
        var sb = new StringBuilder();
        AppendNextSequenceValueOperation(sb, name, schema);
        return sb.ToString();
    }

    /// <summary>
    /// Appends a SQL++ statement that reads the next value from a named sequence.
    /// </summary>
    public override void AppendNextSequenceValueOperation(
        StringBuilder commandStringBuilder,
        string name,
        string? schema)
    {
        commandStringBuilder.Append("SELECT NEXT VALUE FOR ");
        AppendSequenceIdentifier(commandStringBuilder, name, schema);
        commandStringBuilder.AppendLine(SqlGenerationHelper.StatementTerminator);
    }

    /// <summary>
    /// Returns a SQL++ statement that obtains the next value from a named sequence
    /// (equivalent to <see cref="GenerateNextSequenceValueOperation"/> for Couchbase).
    /// </summary>
    public override string GenerateObtainNextSequenceValueOperation(string name, string? schema)
        => GenerateNextSequenceValueOperation(name, schema);

    /// <summary>
    /// Appends a SQL++ statement that obtains the next value from a named sequence
    /// (equivalent to <see cref="AppendNextSequenceValueOperation"/> for Couchbase).
    /// </summary>
    public override void AppendObtainNextSequenceValueOperation(
        StringBuilder commandStringBuilder,
        string name,
        string? schema)
        => AppendNextSequenceValueOperation(commandStringBuilder, name, schema);

    // Emits `schema`.`name` or just `name` when schema is null.
    private void AppendSequenceIdentifier(StringBuilder sb, string name, string? schema)
    {
        if (schema != null)
        {
            SqlGenerationHelper.DelimitIdentifier(sb, schema);
            sb.Append('.');
        }
        SqlGenerationHelper.DelimitIdentifier(sb, name);
    }
}

/* ************************************************************
 *
 *    @author Couchbase <info@couchbase.com>
 *    @copyright 2025 Couchbase, Inc.
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 *
 * ************************************************************/
